name: Build, create release and publish to npmjs

on:
  push:
    tags:
      - "v*.*.*"
      
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install packages
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Set package version from tag
        run: node build-setver.js ${{github.ref_name}}
      - name: Create release bundle
        run: |
          node build-bundle.js
          mv dist/adaptive-streamlines.js dist/adaptive-streamlines-${{github.ref_name}}.js
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/adaptive-streamlines-${{github.ref_name}}.js
      - name: NPM publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
